base_url = "https://az4aaz.github.io/portfolio/"
title = "Lucien HERVE"
description = "I'm Lucien, a computer science student, passionate about software and web development."
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]
theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
comment = false
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/skills", url = "/skills", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/experiences", url = "/experiences", weight = 3 },
]

socials = [
    { name = "github", url = "https://github.com/az4aaz/", icon = "github" },
]

custom_css = []

[extra.analytics]
enabled = false

[extra.analytics.goatcounter]
user = "az4aaz"
host = "goatcounter.com" # default= goatcounter.com
